services:
  - type: web
    name: english-checkin-wall
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_S5xAnYGJL4tH@ep-shy-tooth-atj1kwma-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
